#!/usr/bin/env python3
# Copyright 2025 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
"""Turn the CSV produced by scripts/axi_tree.tcl into a Markdown table and a
graphviz figure of the Chimera AXI infrastructure (crossbars + width/ID
converters + CDCs + endpoints), annotated with the per-port AXI widths.

Usage:
    scripts/axi_tree_report.py --csv axi_tree.csv --outdir build/axi_tree
Produces <outdir>/axi_tree.md, axi_tree.dot and (if `dot` is on PATH)
axi_tree.svg + axi_tree.png.
"""
import argparse
import csv
import os
import re
import shutil
import subprocess
import sys

ROLE_COLOR = {          # graphviz fillcolor per role
    "xbar":    "#cfe8ff",
    "dw_conv": "#ffd9b3",   # data-width converter
    "id_conv": "#fff0a6",   # ID-width converter
    "cdc":     "#e6ccff",
    "atomics": "#ffd6e0",
    "to_mem":  "#d9d9d9",
}
ROLE_LABEL = {
    "xbar": "crossbar", "dw_conv": "data-width conv", "id_conv": "ID-width conv",
    "cdc": "clock-domain crossing", "atomics": "atomics", "to_mem": "AXI→mem/reg",
}


def subsystem(path):
    m = re.search(r"gen_clusters\[(\d+)\]", path)
    if m:
        return f"cluster[{m.group(1)}]"
    if "i_cheshire" in path:
        return "cheshire"
    if re.search(r"mem_?isl|memory_island", path, re.I):
        return "mem_island"
    if re.search(r"hyperbus", path, re.I):
        return "hyperbus"
    return "soc"


def short(path):
    """Human-readable node name: drop the tb prefix, collapse the cluster chain."""
    s = re.sub(r"^/tb_\w+/(fix/)?(dut/)?", "", path)
    s = re.sub(r"i_cluster_domain/gen_clusters\[(\d+)\]/gen_cluster_type/i_chimera_cluster",
               r"cluster[\1]", s)
    s = re.sub(r"gen_\w+?/", "", s)          # drop generate-block noise
    s = s.replace("i_cheshire/", "cheshire/")
    return s


def wtriplet(row, side):
    a, d, i, u = (row[f"{side}_addr"], row[f"{side}_data"],
                  row[f"{side}_id"], row[f"{side}_user"])
    return a, d, i, u


def conv_note(row):
    """Describe the transition a node performs (data/ID/user width change)."""
    notes = []
    for fld, lbl in (("data", "data"), ("id", "ID"), ("user", "user")):
        s, m = row[f"slv_{fld}"], row[f"mst_{fld}"]
        if s and m and s != m:
            notes.append(f"{lbl} {s}→{m}")
    return ", ".join(notes)


def load(csv_path):
    with open(csv_path) as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        r["subsys"] = subsystem(r["path"])
        r["short"] = short(r["path"])
        r["conv"] = conv_note(r)
    return rows


def fmt_side(row, side):
    a, d, i, u = wtriplet(row, side)
    if not any((a, d, i, u)):
        return "–"
    return f"{a or '?'}/{d or '?'}/{i or '?'}/{u or '?'}"


def write_markdown(rows, path):
    order = ["cheshire", "cluster[0]", "cluster[1]", "cluster[2]", "cluster[3]",
             "cluster[4]", "mem_island", "hyperbus", "soc"]
    rows_sorted = sorted(rows, key=lambda r: (order.index(r["subsys"])
                                              if r["subsys"] in order else 99, r["short"]))
    with open(path, "w") as f:
        f.write("# Chimera AXI infrastructure — extracted from the elaborated design\n\n")
        f.write("Generated by `scripts/axi_tree.tcl` + `scripts/axi_tree_report.py` from the "
                "compiled QuestaSim snapshot. Widths are `addr/data/id/user` (bits), read from "
                "the elaborated port signals. Blank side = single-ended (e.g. a CDC source).\n\n")
        f.write("| Subsystem | Node | Module | Role | slv A/D/I/U | mst A/D/I/U | Conversion |\n")
        f.write("|---|---|---|---|---|---|---|\n")
        cur = None
        for r in rows_sorted:
            sub = r["subsys"] if r["subsys"] != cur else ""
            cur = r["subsys"]
            leaf = r["short"].split("/")[-1]
            f.write(f"| {sub} | `{leaf}` | `{r['module']}` | {ROLE_LABEL.get(r['role'], r['role'])} "
                    f"| {fmt_side(r,'slv')} | {fmt_side(r,'mst')} | {r['conv']} |\n")
        f.write(f"\n*{len(rows_sorted)} AXI nodes.*\n")


def nid(path):
    return "n_" + re.sub(r"\W", "_", path)


def write_dot(rows, path):
    by_path = {r["path"]: r for r in rows}
    paths = list(by_path)

    def parent_of(p):
        best = None
        for q in paths:
            if q != p and p.startswith(q + "/"):
                if best is None or len(q) > len(best):
                    best = q
        return best

    subsys_of = {}
    for r in rows:
        subsys_of.setdefault(r["subsys"], []).append(r)

    lines = ['digraph axi_tree {', '  rankdir=LR;', '  node [shape=box, style="rounded,filled", '
             'fontname="Helvetica", fontsize=10];', '  edge [color="#888888"];',
             '  ROOT [label="Chimera SoC AXI", shape=oval, fillcolor="#ffffff"];']
    for sub, rs in subsys_of.items():
        lines.append(f'  subgraph cluster_{re.sub(chr(92)+"W","_",sub)} {{')
        lines.append(f'    label="{sub}"; style=dashed; color="#bbbbbb";')
        for r in rs:
            leaf = r["short"].split("/")[-1]
            conv = ("\\n" + r["conv"]) if r["conv"] else ""
            slv = fmt_side(r, "slv"); mst = fmt_side(r, "mst")
            wl = f"\\nslv {slv}" + (f"\\nmst {mst}" if mst != "–" else "")
            lines.append(f'    {nid(r["path"])} [label="{leaf}\\n[{r["role"]}]{conv}{wl}", '
                         f'fillcolor="{ROLE_COLOR.get(r["role"], "#ffffff")}"];')
        lines.append("  }")
    # containment edges among extracted nodes; roots attach to a per-subsystem anchor
    anchor = {}
    for r in rows:
        p = parent_of(r["path"])
        if p:
            lines.append(f'  {nid(p)} -> {nid(r["path"])};')
        else:
            anchor.setdefault(r["subsys"], r["path"])  # first root of each subsystem
    for sub, p in anchor.items():
        lines.append(f'  ROOT -> {nid(p)} [style=bold, label="{sub}"];')
    # also connect same-subsystem roots so each subsystem reads as one branch
    seen = {}
    for r in rows:
        if not parent_of(r["path"]):
            first = anchor[r["subsys"]]
            if r["path"] != first:
                lines.append(f'  {nid(first)} -> {nid(r["path"])} [style=dotted];')
    lines.append("}")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default="axi_tree.csv")
    ap.add_argument("--outdir", default=".")
    a = ap.parse_args()
    os.makedirs(a.outdir, exist_ok=True)
    rows = load(a.csv)
    if not rows:
        sys.exit("no rows in " + a.csv)
    md = os.path.join(a.outdir, "axi_tree.md")
    dot = os.path.join(a.outdir, "axi_tree.dot")
    write_markdown(rows, md)
    write_dot(rows, dot)
    print(f"wrote {md} and {dot} ({len(rows)} nodes)")
    if shutil.which("dot"):
        for fmt in ("svg", "png"):
            out = os.path.join(a.outdir, f"axi_tree.{fmt}")
            try:
                subprocess.run(["dot", f"-T{fmt}", dot, "-o", out], check=True)
                print(f"wrote {out}")
            except subprocess.CalledProcessError as e:
                print(f"dot -T{fmt} failed: {e}", file=sys.stderr)
    else:
        print("graphviz 'dot' not on PATH; rendered .dot only", file=sys.stderr)


if __name__ == "__main__":
    main()
